# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bece3d475910f9072b2eb7030598d0cc499a50ae3bd3745d6c2a982a30671dafd2c40d2650af3d02fb394208dc9dfb8d7ad296c492c74a5629b09d3c7e871f2

test:
  secret_key_base: 7b917d9ef5bb82a2b33cce72a19c494b0d711ba4381814044a18b8f741e5005b29aab0a2888f8b6039d58ebcc18e4637807d406526e63e7f8bb563cfe77f989a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
